serviceName: "job"

log:
  service: "job"
  host: ""
  caller: false
  stdout: true

tracer:
  tracingType: "jaeger"
  samplerType: "const"
  samplerParam: "1"
  senderType: "udp"
  endpoint: "cyril.develop:6831"

ginServer:
  version: 0.0.1
  host: localhost
  ip: 0.0.0.0
  port: 4040
  timeout: 5
  debug: false
  pprof: true
  readTimeout: "1s"
  writeTimeout: "1s"
  centerAddr:
    - "127.0.0.1:8761"
    - "127.0.0.1:8762"
    - "127.0.0.1:8763"
  centerName: "discovery"
  #  心跳间隔，单位s，默认30s
  renewalIntervalInSecs: 5
  #  获取服务列表间隔，单位s，默认15s
  registryFetchIntervalSeconds: 3
  #  滚动发现地址，单位s，默认60s
  rollDiscoveriesIntervalSeconds: 5
  #  服务过期间隔，单位s, 默认90s
  durationInSecs: 60
  disableAccessLog: false

microServer:
  poolSize: 100
  retries: 1
  poolTTL: 10
  requestTimeout: 5s
  dialTimeout: 5s
  rpcRegister: "eureka"
  rpcModel: "grpc"
  centerAddr:
    - "127.0.0.1:8761"
    - "127.0.0.2:8762"
    - "127.0.0.1:8763"
  disableTracer: false
  enableBreaker: false
  #  服务过期间隔，单位s, 默认30s
  registerTTL: 30
  #  心跳间隔，单位s，默认10s
  registerInterval: 5
  #  获取服务列表间隔，单位s，默认30s
  renewalIntervalInSecs: 3
  #  滚动发现地址，单位s，默认60s
  rollDiscoveriesIntervalSeconds: 5
  dataCenterName: "discovery"
  serverVersion: "1.0.1"
  address: ":10086"
  serverOnly: true


httpClient:
  addr: ":8080"
  timeout: 1s
  readtimeout: 1s
  writetimeout: 1s

redis:
  name: "miooikaak.job"
  proto: "tcp"
  addr: "cyril.develop:6379"
  auth: "RdIwJZKSAh"
  dialTimeout: "200ms"
  readTimeout: "200ms"
  writeTimeout: "200ms"
  expire: "10s"
  pool:
    active: 200
    idle: 200
    idleTimeout: "80s"

db:
  type: "mysql"
  server: "cyril.develop"
  port: 3306
  database: "job"
  user: "root"
  password: "6jrBHdPD6a"
  maxIdleConns: 100
  maxOpenConns: 100
  maxLeftTime: 300s

elastic:
  addrs:
    - "http://cyril.develop:9200"
  username: ""
  password: ""
  healthcheckEnabled: true
  snifferEnabled: false
  healthtimeout: "3s"
  snifferTimeout: "3s"

rocketMq:
  dsn:
    - "cyril.develop:9876"
  namespace: ""
  producer:
    send_msg_timeout: 2s
    retry_times: 2
  consumer:
    consumer_model: 2
    from_where: 1
    consume_orderly: false
    consume_message_batch_max_size: 1
    retry_times: 5
    max_reconsume_times: 5
    auto_commit: false
    tag_expression: ""

zmsUrl: "test"
